# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField()),
                ('cost', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cost.Cost')),
                ('label', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField()),
                ('price_type', models.CharField(choices=[(b'FI', 'fixed'), (b'P/U', 'per_unit')], default=b'FI', max_length=100, null=True)),
                ('unit_name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[(b'B', 'Bakery'), (b'G', 'Grocery'), (b'BU', 'Bulk'), (b'BSFC', 'BSFC'), (b'P', 'Produce'), (b'H&B', 'Health & Beauty'), (b'H', 'Household'), (b'BEV', 'Beverage'), (b'C', 'Chill'), (b'G&G', 'Grab & Go'), (b'FR', 'Frozen')], default=None, max_length=100, null=True)),
            ],
        ),
    ]
