# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 01:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='count',
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 14, 1, 7, 53, 85348, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='revenue',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='revenue.Revenue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='cost.Cost'),
        ),
    ]
