# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discounts',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='discounts.Discounts'),
            preserve_default=False,
        ),
    ]
